server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${SEARCH_PATH:file:///C:/Dev/Spring/microServices/e-commerce/config-server/src/main/resources/config}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

management:
  endpoints:
    web:
      exposure:
        include: ${ENDPOINT_EXPOSER:busrefresh,refresh,health,info}

logging:
  level:
    root: INFO
  file:
    name: logs/config-server/app.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7