spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/MicroServices/ecom-microservices/config-server/src/main/resources/config
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  management:
    endpoints:
      web:
        exposure:
          include: ${ENDPOINT_EXPOSER:health,info}


server:
  port: ${SERVER_PORT:8888}
