server:
  port: ${PORT}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  cloud:
    bus:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: ${SHOW_SQL}
    database-platform: ${DIALECT}

management:
  endpoints:
    web:
      exposure:
        include: ${ENDPOINT_EXPOSER:health,info}
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
    com.main.userservice: TRACE
  file:
    name: logs/user-service/app.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7